force-app/main/default/objects/Campaign_Case__c/Campaign_Case__c.object-meta.xml
<CustomObject>
    <label>Campaign Case</label>
    <nameField>
        <label>Campaign Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Case__c/fields/Customer_Prospect__c.field-meta.xml
<CustomField>
    <fullName>Customer_Prospect__c</fullName>
    <label>Customer Prospect</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Potential Positive</fullName>
            </value>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Potential Negative</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
            <value>
                <fullName>Potential Qualified</fullName>
            </value>
            <value>
                <fullName>Potential Unqualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampaignCaseTriggerHandlerTest.cls
@isTest
public class CampaignCaseTriggerHandlerTest {
    @isTest
    public static void CheckCustomerProspectIfPositive(){
        Campaign_Case__c CampaignCase = new Campaign_Case__c();
        CampaignCase.Description__c = 'I am interested';
        
        
        Test.startTest();
        insert CampaignCase;
        Test.stopTest();
        Campaign_Case__c CamCas = [select Customer_Prospect__c FROM Campaign_Case__c Where Id =: CampaignCase.Id];
        system.assertEquals('Potential Positive',CamCas.Customer_Prospect__c);
    }
        @isTest
        public static void CheckCustomerProspectIfNegative(){
        Campaign_Case__c CampaignCase = new Campaign_Case__c();
        CampaignCase.Description__c = 'I am not interested';
        
        
        Test.startTest();
        insert CampaignCase;
        Test.stopTest();
        
        Campaign_Case__c CamCas = [select Customer_Prospect__c FROM Campaign_Case__c Where Id =: CampaignCase.Id];
        system.assertEquals('Potential Negative',CamCas.Customer_Prospect__c);            
    }
}