force-app/main/default/objects/Campaign_Case__c/Campaign_Case__c.object-meta.xml
<CustomObject>
    <label>Campaign Case</label>
    <nameField>
        <label>Campaign Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Case__c/fields/Customer_Prospect__c.field-meta.xml
<CustomField>
    <fullName>Customer_Prospect__c</fullName>
    <label>Customer Prospect</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Potential Positive</fullName>
            </value>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Potential Negative</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
            <value>
                <fullName>Potential Qualified</fullName>
            </value>
            <value>
                <fullName>Potential Unqualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Not_Interested_List__mdt/Not_Interested_List__mdt.object-meta.xml
<CustomObject>
    <label>Not Interested List</label>
    <pluralLabel>Not Interested Lists</pluralLabel>
</CustomObject>

force-app/main/default/classes/CampaignCaseTriggerHandler.cls
public class CampaignCaseTriggerHandler {

    public static void handleBeforeInsert(List<Campaign_Case__c> newCampaignCase){
    
      List<Not_Interested_List__mdt> lstLabel = Not_Interested_List__mdt.getAll().values();
   
    String str = '';
    Set<String> a  = new Set<String>();
    
    for(Not_Interested_List__mdt nil : lstLabel){
        a.add(nil.Label); 
    }
    
    List<String> idList = new List<String>(a);
    
    for (Campaign_Case__c c : newCampaignCase) {
       
        if(c.Description__c != null)
        {
            for(integer i = 0; i < lstLabel.size();i++) {       
                if(c.Description__c.containsIgnoreCase(idList[i])){
                    
                    c.Customer_Prospect__c = 'Potential Negative';
                    break;
                }
                else{
                    
                    c.Customer_Prospect__c = 'Potential Positive';
                }
            }
            
        }
}
    }
}